#!/usr/bin/env python3
"""corpus.json -> refs.bib

    python make_bib.py lit/corpus.json -o lit/refs.bib
    python make_bib.py lit/corpus.json -o lit/refs.bib --all   # include unverified records

Unverified records are left out by default and listed on stderr. A .bib file is the one artifact that
turns into citations in a submitted paper, so a record that no API confirmed should not be able to
reach it by accident - that is how a plausible-but-wrong citation gets published.

Stdlib only.
"""

import argparse
import json
import pathlib
import re
import sys
from collections import Counter

JOURNALS = {"TDSC", "TIFS", "TOPS"}
PREPRINTS = {"arXiv", "tech-report"}

# Order matters: the backslash must be escaped first or it mangles the others.
LATEX = [("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"), ("$", r"\$"),
         ("#", r"\#"), ("_", r"\_"), ("{", r"\{"), ("}", r"\}"),
         ("~", r"\textasciitilde{}"), ("^", r"\textasciicircum{}")]


def tex(s):
    s = str(s or "")
    for a, b in LATEX:
        s = s.replace(a, b)
    return s


def authors(rec):
    a = rec.get("authors") or []
    if isinstance(a, str):
        a = [x.strip() for x in re.split(r",| and ", a) if x.strip()]
    return " and ".join(tex(x) for x in a)


def entry(rec, key):
    vs = rec.get("venue_short")
    venue = rec.get("venue") or vs or ""
    year = rec.get("year")
    arxiv, doi = rec.get("arxiv_id"), rec.get("doi")

    if vs in PREPRINTS or (not rec.get("peer_reviewed") and not doi):
        kind, venue_field = "misc", None
    elif vs in JOURNALS or (rec.get("type") or "") == "journal-article":
        kind, venue_field = "article", "journal"
    else:
        kind, venue_field = "inproceedings", "booktitle"

    f = []
    if authors(rec):
        f.append(("author", authors(rec)))
    # Double braces protect capitalisation: most styles would otherwise lowercase LLM, MCP, eBPF.
    f.append(("title", "{%s}" % tex(rec.get("title"))))
    if venue_field and venue:
        f.append((venue_field, tex(venue)))
    if year:
        f.append(("year", str(year)))
    if doi:
        f.append(("doi", tex(doi)))
    if arxiv:
        f += [("eprint", tex(arxiv)), ("archivePrefix", "arXiv")]
        if rec.get("primary_category"):
            f.append(("primaryClass", tex(rec["primary_category"])))
    if rec.get("url"):
        f.append(("url", tex(rec["url"])))
    if kind == "misc" and not venue_field and venue and venue != "arXiv":
        f.append(("howpublished", tex(venue)))
    if not rec.get("verified"):
        f.append(("note", "UNVERIFIED: %s" % tex(rec.get("note") or "no API evidence")))

    body = ",\n".join("  %-14s = {%s}" % (k, v) for k, v in f)
    return "@%s{%s,\n%s\n}\n" % (kind, key, body)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("corpus")
    ap.add_argument("-o", "--out", default="refs.bib")
    ap.add_argument("--all", action="store_true",
                    help="include unverified records (marked with a note field)")
    args = ap.parse_args()

    recs = json.loads(pathlib.Path(args.corpus).read_text(encoding="utf-8"))
    if isinstance(recs, dict):
        recs = recs.get("records") or recs.get("corpus") or []

    skipped = [r for r in recs if not r.get("verified")]
    if not args.all:
        recs = [r for r in recs if r.get("verified")]

    # Stable, collision-free keys: same base key gets a, b, c suffixes in corpus order.
    seen, out = Counter(), []
    for r in recs:
        base = re.sub(r"[^A-Za-z0-9:-]", "", r.get("key") or "") or "unkeyed%d" % (len(out) + 1)
        seen[base] += 1
        key = base if seen[base] == 1 else "%s%s" % (base, chr(ord("a") + seen[base] - 2))
        out.append(entry(r, key))

    header = ["% refs.bib - generated by lit-recon make_bib.py",
              "%% %d entries" % len(out)]
    if skipped and not args.all:
        header.append("%% %d unverified record(s) excluded; rerun with --all to include them"
                      % len(skipped))
    pathlib.Path(args.out).write_text(
        "\n".join(header) + "\n\n" + "\n".join(out), encoding="utf-8")

    print("%d entries -> %s" % (len(out), args.out))
    if skipped:
        where = "excluded" if not args.all else "included, marked UNVERIFIED"
        print("%d unverified record(s) %s:" % (len(skipped), where), file=sys.stderr)
        for r in skipped:
            print("  - %s: %s" % (r.get("key") or "?", (r.get("title") or "?")[:70]),
                  file=sys.stderr)


if __name__ == "__main__":
    main()
